name: Majsoul-Login
on:
  workflow_dispatch:
  schedule: #5:00
   - cron: '0 11,17 * * *'
jobs:
  login:
    name: Majsoul-Login
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main  # 替换为你的目标分支

      - name: Install Selenium
        run: pip install selenium==4.17.2

      - name: Majsoul login
        run: python login.py ${{ secrets.EMAIL }} ${{ secrets.PASSWD }}

      - name: Commit and push log file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add log.txt
          git commit -m "Update log file [skip ci]"
          git push origin main  # 替换为你的目标分支
